apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
  labels:
    app: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible-test
        image: meencloud/ansible-test
        ports:
        - containerPort: 80
